'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Eye, EyeOff, LockKeyhole, Mail, MapPin, ShieldCheck } from 'lucide-react';
import { ADMIN_TOKEN_STORAGE_KEY, getApiErrorMessage, hireProApi, saveAdminToken } from '../../lib/api';

export default function AdminLoginPage(){
 const router=useRouter(); const [email,setEmail]=useState('admin@hirepro.com'),[password,setPassword]=useState(''),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const auth=await hireProApi.admin.signin({email,password});saveAdminToken(auth.access_token);const requestedPath=new URLSearchParams(window.location.search).get('next');router.replace(requestedPath?.startsWith('/admin/')?requestedPath:'/admin/dashboard')}catch(err){localStorage.removeItem(ADMIN_TOKEN_STORAGE_KEY);hireProApi.setToken(null);setError(getApiErrorMessage(err,'Unable to sign in.'))}finally{setLoading(false)}};
 return <main className="grid min-h-screen bg-[#F5F6F8] lg:grid-cols-[1.05fr_.95fr]">
  <section className="relative hidden overflow-hidden bg-gradient-to-br from-[#171456] to-[#0B0A2D] p-12 text-white lg:flex lg:flex-col"><div className="absolute -left-24 bottom-10 size-80 rounded-full border border-white/[.06]"/><div className="absolute -left-8 bottom-28 size-52 rounded-full border border-[#0F9D8C]/20"/><Link href="/" className="relative flex items-center gap-3 font-sora text-xl font-bold"><span className="grid size-10 place-items-center rounded-lg bg-[#0F9D8C]"><MapPin size={19}/></span>HirePro</Link><div className="relative my-auto max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-xs font-semibold text-[#75D8CC]"><ShieldCheck size={14}/>SECURE ADMINISTRATION</span><h1 className="mt-6 font-sora text-5xl font-bold leading-[1.08] tracking-[-.04em]">Keep the marketplace trusted.</h1><p className="mt-5 max-w-md text-base leading-7 text-white/55">A protected workspace for HirePro platform operations, verification, moderation, and support.</p></div><p className="relative text-xs text-white/30">Authorized HirePro personnel only</p></section>
  <section className="flex items-center justify-center p-6 md:p-12"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center gap-2 font-sora text-xl font-bold text-[#1E1B6E] lg:hidden"><MapPin/>HirePro</Link><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">Admin console</p><h2 className="mt-3 font-sora text-3xl font-bold tracking-[-.03em] text-[#19192D]">Sign in to continue</h2><p className="mt-2 text-sm text-[#667085]">Use your administrator credentials.</p></div>{error&&<div role="alert" className="mb-5 rounded-lg border border-[#F3C9BD] bg-[#FDEDE8] p-3 text-sm text-[#B7472D]">{error}</div>}<form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#344054]">Email address</span><span className="relative block"><Mail size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-lg border border-[#D8DCE4] bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-[#0F9D8C] focus:ring-2 focus:ring-[#0F9D8C]/10" placeholder="admin@hirepro.com"/></span></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#344054]">Password</span><span className="relative block"><LockKeyhole size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input required type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-lg border border-[#D8DCE4] bg-white py-3 pl-10 pr-11 text-sm outline-none focus:border-[#0F9D8C] focus:ring-2 focus:ring-[#0F9D8C]/10" placeholder="Enter your password"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[#98A0AF]" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><button disabled={loading} className="w-full rounded-lg bg-[#0F9D8C] py-3 text-sm font-semibold text-white transition hover:bg-[#0C897A] disabled:opacity-60">{loading?'Verifying access…':'Access admin console'}</button></form><p className="mt-7 text-center text-xs text-[#8A91A1]">Customer or provider? <Link href="/login" className="font-semibold text-[#0F9D8C]">Use regular sign in</Link></p></div></section>
 </main>
}
