'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BadgeCheck, Ban, BriefcaseBusiness, Building2, CalendarDays, Eye, Mail, RefreshCw, Search, Star, TrendingUp, UserCheck, Users } from 'lucide-react';
import { AdminStats, Business, getApiErrorMessage, hireProApi, Json, User } from '../lib/api';
import { DashboardCard, StatusBadge } from './dashboard/ui';

type ManagedUser = User & { is_active?: boolean; status?: string; last_login_at?: string | null; business_count?: number };
type ManagedBusiness = Business & { category?: { name?: string } | string; owner?: { full_name?: string; email?: string }; rating?: number; review_count?: number; status?: string };

const inputClass='w-full rounded-lg border border-[#D8DCE4] bg-white px-3 py-2.5 text-sm outline-none transition focus:border-[#0F9D8C] focus:ring-2 focus:ring-[#0F9D8C]/10';

function Header({eyebrow,title,copy,onRefresh,loading}:{eyebrow:string;title:string;copy:string;onRefresh:()=>void;loading:boolean}){
 return <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">{eyebrow}</p><h1 className="mt-2 font-sora text-3xl font-bold">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#667085]">{copy}</p></div><button onClick={onRefresh} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-lg border border-[#D8DCE4] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-60"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button></header>
}
function ErrorBanner({message}:{message:string}){return message?<div role="alert" className="mb-5 rounded-lg border border-[#F3C9BD] bg-[#FDEDE8] p-4 text-sm text-[#B7472D]">{message}</div>:null}
function Empty({title,copy}:{title:string;copy:string}){return <div className="grid min-h-60 place-items-center p-8 text-center"><div><Search className="mx-auto text-[#98A0AF]"/><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-sm text-[#8A91A1]">{copy}</p></div></div>}
function Metric({label,value,icon,detail}:{label:string;value:string|number;icon:React.ReactNode;detail:string}){return <DashboardCard className="rounded-xl p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-[#667085]">{label}</p><p className="mt-2 font-sora text-3xl font-bold tabular-nums">{value}</p></div><span className="grid size-10 place-items-center rounded-lg bg-[#ECF8F6] text-[#0F9D8C]">{icon}</span></div><p className="mt-3 text-xs text-[#8A91A1]">{detail}</p></DashboardCard>}

export function AdminUsersManagement(){
 const [items,setItems]=useState<ManagedUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[role,setRole]=useState('all'),[status,setStatus]=useState('all'),[busy,setBusy]=useState(''),[selected,setSelected]=useState<ManagedUser|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await hireProApi.admin.list('users',{limit:100}) as unknown as ManagedUser[])}catch(e){setError(getApiErrorMessage(e,'Unable to load users. The backend must provide GET /admin/users.'))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const active=(u:ManagedUser)=>u.is_active!==false&&!['suspended','blocked','inactive'].includes((u.status??'').toLowerCase());
 const filtered=useMemo(()=>items.filter(u=>(!query||`${u.full_name} ${u.email}`.toLowerCase().includes(query.toLowerCase()))&&(role==='all'||u.role===role)&&(status==='all'||(status==='active'?active(u):!active(u)))),[items,query,role,status]);
 const setUserActive=async(user:ManagedUser,value:boolean)=>{setBusy(user.id);setError('');try{const updated=await hireProApi.admin.update('users',user.id,{is_active:value,status:value?'active':'suspended'}) as unknown as ManagedUser;setItems(list=>list.map(x=>x.id===user.id?{...x,...updated,is_active:value,status:value?'active':'suspended'}:x));setSelected(x=>x?.id===user.id?{...x,...updated,is_active:value,status:value?'active':'suspended'}:x)}catch(e){setError(getApiErrorMessage(e,`Unable to ${value?'activate':'suspend'} this user.`))}finally{setBusy('')}};
 const customers=items.filter(u=>u.role==='customer').length, providers=items.filter(u=>u.role==='business').length, suspended=items.filter(u=>!active(u)).length;
 return <div><Header eyebrow="People" title="User management" copy="Search customer and provider accounts, inspect account details, and control platform access." onRefresh={load} loading={loading}/><ErrorBanner message={error}/>
 <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total users" value={items.length} icon={<Users size={20}/>} detail="All registered accounts"/><Metric label="Customers" value={customers} icon={<UserCheck size={20}/>} detail="Service-seeking accounts"/><Metric label="Providers" value={providers} icon={<BriefcaseBusiness size={20}/>} detail="Business-owner accounts"/><Metric label="Suspended" value={suspended} icon={<Ban size={20}/>} detail="Accounts without access"/></section>
 <DashboardCard className="overflow-hidden rounded-xl"><div className="grid gap-3 border-b border-[#E4E7EC] p-4 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email" className={`${inputClass} pl-9`}/></label><select value={role} onChange={e=>setRole(e.target.value)} className={inputClass}><option value="all">All account types</option><option value="customer">Customers</option><option value="business">Providers</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className={inputClass}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div>
 {loading?<Rows/>:filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#F8F9FB] text-xs text-[#667085]"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Account type</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#ECEEF2]">{filtered.map(user=><tr key={user.id} className="hover:bg-[#FAFBFC]"><td className="px-5 py-4"><button onClick={()=>setSelected(user)} className="text-left"><span className="block font-semibold text-[#222235]">{user.full_name||'Unnamed user'}</span><span className="mt-0.5 block text-xs text-[#8A91A1]">{user.email}</span></button></td><td className="px-5 py-4 capitalize">{user.role==='business'?'Provider':'Customer'}{user.is_admin&&<span className="ml-2 text-xs text-[#0F9D8C]">Admin</span>}</td><td className="px-5 py-4 text-[#667085]">{date(user.created_at)}</td><td className="px-5 py-4">{active(user)?<StatusBadge tone="success">Active</StatusBadge>:<StatusBadge tone="danger">Suspended</StatusBadge>}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>setSelected(user)} className="rounded-md border border-[#D8DCE4] p-2" aria-label="View user"><Eye size={15}/></button>{!user.is_admin&&<button disabled={busy===user.id} onClick={()=>setUserActive(user,!active(user))} className={`rounded-md px-3 py-2 text-xs font-semibold ${active(user)?'border border-[#F3C9BD] text-[#B7472D]':'bg-[#0F9D8C] text-white'}`}>{active(user)?'Suspend':'Activate'}</button>}</div></td></tr>)}</tbody></table></div>:<Empty title="No users found" copy="Try a different search or filter."/>}</DashboardCard>
 {selected&&<Drawer title="User details" onClose={()=>setSelected(null)}><Detail label="Full name" value={selected.full_name}/><Detail label="Email" value={selected.email}/><Detail label="Account type" value={selected.role==='business'?'Provider':'Customer'}/><Detail label="Joined" value={date(selected.created_at)}/><Detail label="Last login" value={date(selected.last_login_at)}/><div className="mt-6 flex gap-2">{!selected.is_admin&&<button disabled={busy===selected.id} onClick={()=>setUserActive(selected,!active(selected))} className={`w-full rounded-lg px-4 py-3 text-sm font-semibold ${active(selected)?'border border-[#F3C9BD] text-[#B7472D]':'bg-[#0F9D8C] text-white'}`}>{active(selected)?'Suspend account':'Activate account'}</button>}<a href={`mailto:${selected.email}`} className="grid size-11 shrink-0 place-items-center rounded-lg border border-[#D8DCE4]"><Mail size={17}/></a></div></Drawer>}</div>
}

export function AdminBusinessesManagement(){
 const [items,setItems]=useState<ManagedBusiness[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[verification,setVerification]=useState('all'),[status,setStatus]=useState('all'),[busy,setBusy]=useState(''),[selected,setSelected]=useState<ManagedBusiness|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await hireProApi.admin.list('businesses',{limit:100}) as unknown as ManagedBusiness[])}catch(e){setError(getApiErrorMessage(e,'Unable to load businesses. The backend must provide GET /admin/businesses.'))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>items.filter(b=>(!query||`${b.name} ${b.city} ${b.owner?.full_name??''}`.toLowerCase().includes(query.toLowerCase()))&&(verification==='all'||(verification==='verified'?b.is_verified:!b.is_verified))&&(status==='all'||(status==='active'?b.is_active:b.is_active===false))),[items,query,verification,status]);
 const update=async(b:ManagedBusiness,body:Json)=>{setBusy(b.id);setError('');try{const updated=await hireProApi.admin.update('businesses',b.id,body) as unknown as ManagedBusiness;setItems(list=>list.map(x=>x.id===b.id?{...x,...body,...updated}:x));setSelected(x=>x?.id===b.id?{...x,...body,...updated}:x)}catch(e){setError(getApiErrorMessage(e,'Unable to update this business.'))}finally{setBusy('')}};
 const setVerified=async(b:ManagedBusiness,value:boolean)=>{setBusy(b.id);setError('');try{const updated=await hireProApi.admin.verifyBusiness(b.id,value) as unknown as ManagedBusiness;const next={...b,...updated,is_verified:value};setItems(list=>list.map(x=>x.id===b.id?{...x,...next}:x));setSelected(x=>x?.id===b.id?{...x,...next}:x)}catch(e){setError(getApiErrorMessage(e,'Unable to update this business verification.'))}finally{setBusy('')}};
 const verified=items.filter(b=>b.is_verified).length, inactive=items.filter(b=>b.is_active===false).length, views=items.reduce((sum,b)=>sum+(Number(b.view_count)||0),0);
 return <div><Header eyebrow="Marketplace" title="Business management" copy="Review every listing, control verification and visibility, and inspect provider performance." onRefresh={load} loading={loading}/><ErrorBanner message={error}/><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Listings" value={items.length} icon={<Building2 size={20}/>} detail="All business profiles"/><Metric label="Verified" value={verified} icon={<BadgeCheck size={20}/>} detail="Approved trusted listings"/><Metric label="Pending" value={items.length-verified} icon={<Activity size={20}/>} detail="Awaiting verification"/><Metric label="Profile views" value={compact(views)} icon={<Eye size={20}/>} detail={`${inactive} inactive listings`}/></section>
 <DashboardCard className="overflow-hidden rounded-xl"><div className="grid gap-3 border-b border-[#E4E7EC] p-4 md:grid-cols-[1fr_190px_180px]"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search business, city, or owner" className={`${inputClass} pl-9`}/></label><select value={verification} onChange={e=>setVerification(e.target.value)} className={inputClass}><option value="all">All verification</option><option value="verified">Verified</option><option value="pending">Pending</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className={inputClass}><option value="all">All visibility</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
 {loading?<Rows/>:filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#F8F9FB] text-xs text-[#667085]"><tr><th className="px-5 py-3">Business</th><th className="px-5 py-3">Owner</th><th className="px-5 py-3">Location</th><th className="px-5 py-3">Performance</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#ECEEF2]">{filtered.map(b=><tr key={b.id} className="hover:bg-[#FAFBFC]"><td className="px-5 py-4"><button onClick={()=>setSelected(b)} className="text-left"><span className="block font-semibold">{b.name}</span><span className="mt-0.5 block text-xs text-[#8A91A1]">{category(b)}</span></button></td><td className="px-5 py-4"><span className="block">{b.owner?.full_name||'Owner unavailable'}</span><span className="text-xs text-[#8A91A1]">{b.owner?.email}</span></td><td className="px-5 py-4 text-[#667085]">{b.city||'—'}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1"><Star size={14} className="text-amber-500"/>{Number(b.rating||0).toFixed(1)}</span><span className="ml-3 text-xs text-[#8A91A1]">{compact(b.view_count||0)} views</span></td><td className="px-5 py-4"><div className="flex gap-1.5">{b.is_verified?<StatusBadge tone="success">Verified</StatusBadge>:<StatusBadge tone="warning">Pending</StatusBadge>}{b.is_active===false&&<StatusBadge tone="danger">Hidden</StatusBadge>}</div></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>setSelected(b)} className="rounded-md border border-[#D8DCE4] p-2"><Eye size={15}/></button><button disabled={busy===b.id} onClick={()=>setVerified(b,!b.is_verified)} className="rounded-md border border-[#D8DCE4] px-3 py-2 text-xs font-semibold">{b.is_verified?'Unverify':'Verify'}</button><button disabled={busy===b.id} onClick={()=>update(b,{is_active:b.is_active===false})} className={`rounded-md px-3 py-2 text-xs font-semibold ${b.is_active===false?'bg-[#0F9D8C] text-white':'border border-[#F3C9BD] text-[#B7472D]'}`}>{b.is_active===false?'Restore':'Hide'}</button></div></td></tr>)}</tbody></table></div>:<Empty title="No businesses found" copy="Try a different search or filter."/>}</DashboardCard>
 {selected&&<Drawer title="Business details" onClose={()=>setSelected(null)}><Detail label="Business" value={selected.name}/><Detail label="Category" value={category(selected)}/><Detail label="Owner" value={selected.owner?.full_name||selected.owner?.email}/><Detail label="Location" value={[selected.address,selected.city].filter(Boolean).join(', ')}/><Detail label="Created" value={date(selected.created_at)}/><Detail label="Profile views" value={String(selected.view_count||0)}/><Detail label="Website" value={selected.website}/><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-[#8A91A1]">Description</p><p className="mt-2 text-sm leading-6 text-[#475467]">{selected.description||'No description supplied.'}</p><div className="mt-6 grid grid-cols-2 gap-2"><button disabled={busy===selected.id} onClick={()=>setVerified(selected,!selected.is_verified)} className="rounded-lg border border-[#D8DCE4] px-4 py-3 text-sm font-semibold">{selected.is_verified?'Remove verification':'Approve verification'}</button><button disabled={busy===selected.id} onClick={()=>update(selected,{is_active:selected.is_active===false})} className={`rounded-lg px-4 py-3 text-sm font-semibold ${selected.is_active===false?'bg-[#0F9D8C] text-white':'border border-[#F3C9BD] text-[#B7472D]'}`}>{selected.is_active===false?'Restore listing':'Hide listing'}</button></div></Drawer>}</div>
}

type SeriesPoint={label:string;value:number};
type AnalyticsData={stats:AdminStats;growth:SeriesPoint[];topBusinesses:Array<{id?:string;name:string;views:number;quotes:number;rating:number}>;conversion:{page_views:number;business_clicks:number;quote_requests:number}};
export function AdminAnalyticsManagement({fallbackStats}:{fallbackStats:AdminStats|null}){
 const emptyStats=fallbackStats??{users:0,businesses:0,reviews:0,quotes:0,open_contact_messages:0};
 const [data,setData]=useState<AnalyticsData>({stats:emptyStats,growth:[],topBusinesses:[],conversion:{page_views:0,business_clicks:0,quote_requests:0}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[range,setRange]=useState('30d');
 const load=useCallback(async()=>{setLoading(true);setError('');const [stats,growth,top,conversion]=await Promise.allSettled([hireProApi.admin.stats(),hireProApi.admin.analytics('growth',{range}),hireProApi.admin.analytics('top-businesses',{range,limit:8}),hireProApi.admin.analytics('conversion',{range})]);const missing:string[]=[];const metric=<T,>(result:PromiseSettledResult<unknown>,fallback:T,name:string)=>{if(result.status==='rejected'){missing.push(name);return fallback}return result.value as T};setData({stats:metric(stats,emptyStats,'summary'),growth:normaliseSeries(metric(growth,[],'growth')),topBusinesses:normaliseBusinesses(metric(top,[],'top businesses')),conversion:normaliseConversion(metric(conversion,{},'conversion'))});setError(missing.length?`Some analytics could not be loaded: ${missing.join(', ')}. Available data is shown below.`:'');setLoading(false)},[range]);useEffect(()=>{void load()},[load]);
 const max=Math.max(...data.growth.map(x=>x.value),1), clickRate=percent(data.conversion.business_clicks,data.conversion.page_views), quoteRate=percent(data.conversion.quote_requests,data.conversion.business_clicks);
 return <div><Header eyebrow="Insights" title="Platform analytics" copy="A structured view of marketplace growth, engagement, conversion, and business performance." onRefresh={load} loading={loading}/><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><ErrorBanner message={error}/><label className="ml-auto flex items-center gap-2 text-sm font-semibold text-[#475467]"><CalendarDays size={16}/><select value={range} onChange={e=>setRange(e.target.value)} className="rounded-lg border border-[#D8DCE4] bg-white px-3 py-2"><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="12m">Last 12 months</option></select></label></div>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Registered users" value={compact(data.stats.users)} icon={<Users size={20}/>} detail="Customer and provider accounts"/><Metric label="Listed businesses" value={compact(data.stats.businesses)} icon={<Building2 size={20}/>} detail="Marketplace supply"/><Metric label="Reviews" value={compact(data.stats.reviews)} icon={<Star size={20}/>} detail="Published marketplace feedback"/><Metric label="Quote requests" value={compact(data.stats.quotes)} icon={<TrendingUp size={20}/>} detail="Customer demand generated"/></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><DashboardCard className="rounded-xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-sora text-lg font-bold">User growth</h2><p className="mt-1 text-xs text-[#8A91A1]">New registrations over the selected period</p></div><StatusBadge tone="neutral">{range}</StatusBadge></div>{data.growth.length?<div className="mt-8 flex h-60 items-end gap-2 border-b border-[#E4E7EC]">{data.growth.map((point,i)=><div key={`${point.label}-${i}`} className="group flex h-full min-w-0 flex-1 items-end"><div title={`${point.label}: ${point.value}`} style={{height:`${Math.max((point.value/max)*100,3)}%`}} className="relative w-full rounded-t bg-[#0F9D8C] opacity-80 transition hover:opacity-100"><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] font-bold group-hover:block">{point.value}</span></div></div>)}</div>:<Empty title="Growth data unavailable" copy="Connect GET /admin/analytics/growth to display the chart."/>}</DashboardCard><DashboardCard className="rounded-xl p-5"><h2 className="font-sora text-lg font-bold">Conversion funnel</h2><p className="mt-1 text-xs text-[#8A91A1]">From discovery to customer intent</p><div className="mt-6 space-y-5"><Funnel label="Homepage views" value={data.conversion.page_views} width={100}/><Funnel label="Business clicks" value={data.conversion.business_clicks} width={Math.max(Number(clickRate),8)} rate={`${clickRate}% of views`}/><Funnel label="Quote requests" value={data.conversion.quote_requests} width={Math.max(Number(quoteRate),8)} rate={`${quoteRate}% of clicks`}/></div></DashboardCard></section>
 <DashboardCard className="mt-6 overflow-hidden rounded-xl"><div className="border-b border-[#E4E7EC] p-5"><h2 className="font-sora text-lg font-bold">Top-performing businesses</h2><p className="mt-1 text-xs text-[#8A91A1]">Ranked by profile views and customer activity</p></div>{data.topBusinesses.length?<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#F8F9FB] text-xs text-[#667085]"><tr><th className="px-5 py-3">Rank</th><th className="px-5 py-3">Business</th><th className="px-5 py-3">Views</th><th className="px-5 py-3">Quotes</th><th className="px-5 py-3">Rating</th><th className="px-5 py-3">View-to-quote</th></tr></thead><tbody className="divide-y divide-[#ECEEF2]">{data.topBusinesses.map((b,i)=><tr key={b.id??`${b.name}-${i}`}><td className="px-5 py-4 font-bold text-[#0F9D8C]">#{i+1}</td><td className="px-5 py-4 font-semibold">{b.name}</td><td className="px-5 py-4 tabular-nums">{compact(b.views)}</td><td className="px-5 py-4 tabular-nums">{compact(b.quotes)}</td><td className="px-5 py-4">{b.rating.toFixed(1)}</td><td className="px-5 py-4">{percent(b.quotes,b.views)}%</td></tr>)}</tbody></table></div>:<Empty title="No business performance data" copy="Connect GET /admin/analytics/top-businesses to populate this ranking."/>}</DashboardCard></div>
}

function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <><button className="fixed inset-0 z-50 bg-[#101828]/35" onClick={onClose} aria-label="Close details"/><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-[#E4E7EC] pb-4"><h2 className="font-sora text-xl font-bold">{title}</h2><button onClick={onClose} className="rounded-lg border border-[#D8DCE4] px-3 py-2 text-sm font-semibold">Close</button></div><div className="mt-5">{children}</div></aside></>}
function Detail({label,value}:{label:string;value:unknown}){return <div className="border-b border-[#EEF0F3] py-3"><p className="text-xs font-semibold uppercase tracking-wide text-[#8A91A1]">{label}</p><p className="mt-1 break-words text-sm font-medium text-[#344054]">{value?String(value):'—'}</p></div>}
function Rows(){return <div className="animate-pulse divide-y divide-[#ECEEF2]">{[1,2,3,4,5].map(i=><div key={i} className="flex gap-5 p-5"><div className="h-4 w-1/3 rounded bg-[#EEF0F3]"/><div className="h-4 w-1/5 rounded bg-[#EEF0F3]"/><div className="ml-auto h-4 w-24 rounded bg-[#EEF0F3]"/></div>)}</div>}
function Funnel({label,value,width,rate}:{label:string;value:number;width:number;rate?:string}){return <div><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-[#475467]">{label}</span><span className="tabular-nums text-[#667085]">{compact(value)}{rate?` · ${rate}`:''}</span></div><div className="h-3 overflow-hidden rounded-full bg-[#EEF0F3]"><div className="h-full rounded-full bg-gradient-to-r from-[#1E1B6E] to-[#0F9D8C]" style={{width:`${Math.min(width,100)}%`}}/></div></div>}
function date(value?:string|null){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function compact(value:number){return new Intl.NumberFormat(undefined,{notation:value>=1000?'compact':'standard',maximumFractionDigits:1}).format(value)}
function percent(a:number,b:number){return b?((a/b)*100).toFixed(1):'0.0'}
function category(b:ManagedBusiness){return typeof b.category==='string'?b.category:b.category?.name||b.category_id||'Uncategorised'}
function normaliseSeries(value:unknown):SeriesPoint[]{const nested=value&&typeof value==='object'?(value as Json).series:undefined;const source:unknown[]=Array.isArray(value)?value:Array.isArray(nested)?nested:[];return source.map((x,i)=>{const row=x as Json;return{label:String(row.label??row.date??row.month??i+1),value:Number(row.value??row.users??row.count??0)}})}
function normaliseBusinesses(value:unknown):AnalyticsData['topBusinesses']{const nested=value&&typeof value==='object'?(value as Json).businesses:undefined;const source:unknown[]=Array.isArray(value)?value:Array.isArray(nested)?nested:[];return source.map((x,i)=>{const row=x as Json;return{id:String(row.id??i),name:String(row.name??'Unnamed business'),views:Number(row.views??row.view_count??0),quotes:Number(row.quotes??row.quote_count??0),rating:Number(row.rating??row.average_rating??0)}})}
function normaliseConversion(value:unknown):AnalyticsData['conversion']{const row=value&&typeof value==='object'?value as Json:{};return{page_views:Number(row.page_views??row.views??0),business_clicks:Number(row.business_clicks??row.clicks??0),quote_requests:Number(row.quote_requests??row.quotes??0)}}
