'use client';

import { useEffect, useMemo, useState } from 'react';
import { Download, ExternalLink, FileCheck2, FileText, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { Business, getApiErrorMessage, hireProApi, Json } from '../lib/api';
import { DashboardCard, StatusBadge } from './dashboard/ui';

type ReviewDocument={id:string;type:string;label:string;fileName:string;status:string;url:string};

export default function AdminVerificationManagement({businesses,onDecided}:{businesses:Business[];onDecided:(businessId:string)=>void}){
 const [selected,setSelected]=useState<Business|null>(null);
 return <div>
  <header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">Trust & safety</p><h1 className="mt-2 font-sora text-3xl font-bold">Business verification</h1><p className="mt-2 text-sm text-[#667085]">Review identity and professional credentials before making a verification decision.</p></header>
  <DashboardCard className="overflow-hidden rounded-xl">
   <div className="flex items-center justify-between border-b border-[#E4E7EC] p-5"><div><h2 className="font-sora text-lg font-bold">Pending applications</h2><p className="mt-1 text-xs text-[#8A91A1]">A document review is required before approval.</p></div><StatusBadge tone={businesses.length?'warning':'success'}>{businesses.length} pending</StatusBadge></div>
   {businesses.length?<div className="divide-y divide-[#ECEEF2]">{businesses.map(business=><div key={business.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-[#EAF8F5] text-[#0F9D8C]"><ShieldCheck size={20}/></span><div className="min-w-0 flex-1"><p className="font-semibold">{business.name}</p><p className="mt-1 text-xs text-[#8A91A1]">{business.city||'Location unavailable'} · submitted {formatDate(business.verification_submitted_at??business.created_at)}</p></div><button onClick={()=>setSelected(business)} className="rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-sm font-semibold text-white">Review documents</button></div>)}</div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><FileCheck2 size={38} className="mx-auto text-[#0F9D8C]"/><p className="mt-4 font-semibold">No verification applications pending</p><p className="mt-1 text-sm text-[#8A91A1]">New document submissions will appear here.</p></div></div>}
  </DashboardCard>
  {selected&&<VerificationReviewDrawer business={selected} onClose={()=>setSelected(null)} onDecided={()=>{onDecided(selected.id);setSelected(null)}}/>}
 </div>;
}

export function VerificationReviewDrawer({business,onClose,onDecided}:{business:Business;onClose:()=>void;onDecided:()=>void}){
 const [detail,setDetail]=useState<Json|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(''),[documentBusy,setDocumentBusy]=useState(''),[reviewed,setReviewed]=useState<string[]>([]);
 const load=async()=>{setLoading(true);setError('');try{setDetail(await hireProApi.admin.verificationDetail(business.id))}catch(e){setError(getApiErrorMessage(e,'Unable to load submitted verification documents.'))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[business.id]);
 const documents=useMemo(()=>normaliseDocuments(detail),[detail]),hasCnic=documents.some(document=>isCnic(document.type)),hasCertificate=documents.some(document=>isCertificate(document.type)),ready=hasCnic&&hasCertificate,reviewedCnic=documents.some(document=>isCnic(document.type)&&reviewed.includes(documentKey(document))),reviewedCertificate=documents.some(document=>isCertificate(document.type)&&reviewed.includes(documentKey(document))),reviewComplete=ready&&reviewedCnic&&reviewedCertificate;
 const decision=async(verified:boolean)=>{const rejectionReason=reason.trim();if(!verified&&rejectionReason.length<3){setError('Enter a rejection reason of at least 3 characters so the provider knows what to correct.');return}if(verified&&!reviewComplete){setError('Open and review both the CNIC and professional certificate before approval.');return}setBusy(verified?'approve':'reject');setError('');try{await hireProApi.admin.verifyBusiness(business.id,verified,verified?undefined:rejectionReason);onDecided()}catch(e){setError(getApiErrorMessage(e,'Unable to save the verification decision.'))}finally{setBusy('')}};
 const openDocument=async(document:ReviewDocument,download:boolean)=>{const key=documentKey(document);setDocumentBusy(key);setError('');try{let value:unknown=document.url;if(document.id)value=await hireProApi.admin.verificationDocument(business.id,document.id);const url=extractDocumentUrl(value);if(!url)throw new Error('The backend did not return a secure document URL.');if(download){const anchor=window.document.createElement('a');anchor.href=url;anchor.target='_blank';anchor.rel='noopener noreferrer';anchor.download=document.fileName||'verification-document';anchor.click()}else window.open(url,'_blank','noopener,noreferrer');setReviewed(current=>current.includes(key)?current:[...current,key])}catch(e){setError(getApiErrorMessage(e,'Unable to open this verification document.'))}finally{setDocumentBusy('')}};
 const status=detailStatus(detail,business);
 return <><button className="fixed inset-0 z-50 bg-[#101828]/40" onClick={onClose} aria-label="Close verification review"/><aside className="fixed inset-y-0 right-0 z-50 w-full max-w-2xl overflow-y-auto bg-white shadow-2xl">
  <header className="sticky top-0 z-10 flex items-start gap-4 border-b border-[#E4E7EC] bg-white p-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#EAF8F5] text-[#0F9D8C]"><ShieldCheck/></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-wide text-[#0F9D8C]">Verification review</p><h2 className="mt-1 truncate font-sora text-xl font-bold">{business.name}</h2><p className="mt-1 text-xs text-[#8A91A1]">{business.city||'Location unavailable'} · {formatDate(business.verification_submitted_at??business.created_at)}</p></div><button onClick={onClose} className="rounded-lg border border-[#D8DCE4] p-2" aria-label="Close"><X size={18}/></button></header>
  <div className="space-y-6 p-6">{error&&<div role="alert" className="rounded-lg border border-[#F3C9BD] bg-[#FDEDE8] p-3 text-sm text-[#B7472D]">{error}</div>}
   <div className="flex items-center justify-between rounded-xl border border-[#E4E7EC] p-4"><div><p className="text-xs text-[#8A91A1]">Application status</p><p className="mt-1 text-sm font-semibold capitalize">{status}</p></div><StatusBadge tone={status==='approved'||status==='verified'?'success':status==='rejected'?'danger':'warning'}>{status}</StatusBadge></div>
   <section><div className="flex items-center justify-between"><div><h3 className="font-sora text-lg font-bold">Submitted documents</h3><p className="mt-1 text-xs text-[#8A91A1]">Open each secure document before making a decision.</p></div><button onClick={load} disabled={loading} className="rounded-lg border border-[#D8DCE4] p-2" aria-label="Refresh documents"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div>
    {loading?<div className="mt-4 space-y-3">{[1,2].map(item=><div key={item} className="h-24 animate-pulse rounded-xl bg-[#F2F4F7]"/>)}</div>:documents.length?<div className="mt-4 space-y-3">{documents.map((document,index)=>{const key=documentKey(document),wasReviewed=reviewed.includes(key);return <div key={`${document.id}-${document.type}-${index}`} className="rounded-xl border border-[#E4E7EC] p-4"><div className="flex flex-wrap items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#F2F4F7] text-[#667085]"><FileText size={18}/></span><div className="min-w-0 flex-1"><p className="font-semibold">{document.label}</p><p className="mt-1 truncate text-xs text-[#8A91A1]">{document.fileName||'Secure provider document'}</p></div><StatusBadge tone={wasReviewed?'success':document.status==='rejected'?'danger':document.status==='approved'?'success':'neutral'}>{wasReviewed?'Reviewed':document.status}</StatusBadge></div><div className="mt-4 flex gap-2"><button disabled={documentBusy===key} onClick={()=>openDocument(document,false)} className="inline-flex items-center gap-2 rounded-lg border border-[#D8DCE4] px-3 py-2 text-xs font-semibold"><ExternalLink size={14}/>View securely</button><button disabled={documentBusy===key} onClick={()=>openDocument(document,true)} className="inline-flex items-center gap-2 rounded-lg border border-[#D8DCE4] px-3 py-2 text-xs font-semibold"><Download size={14}/>Download</button></div></div>})}</div>:<div className="mt-4 rounded-xl border border-dashed border-[#F3C9BD] bg-[#FFF8F6] p-5 text-sm text-[#B5472D]">No submitted documents were returned by the verification-detail API. Approval remains blocked.</div>}
   </section>
   <section className="rounded-xl border border-[#E4E7EC] p-4"><label className="block"><span className="text-sm font-semibold">Rejection reason</span><span className="mt-1 block text-xs text-[#8A91A1]">Required when rejecting. This message will be available to the provider.</span><textarea value={reason} onChange={event=>setReason(event.target.value)} rows={4} maxLength={1000} placeholder="Explain what is missing, expired, or unclear…" className="mt-3 w-full rounded-lg border border-[#D8DCE4] p-3 text-sm outline-none focus:border-[#0F9D8C]"/></label><p className="mt-1 text-right text-[11px] text-[#98A0AF]">{reason.length}/1000</p></section>
   <div className="flex flex-col-reverse gap-3 border-t border-[#E4E7EC] pt-5 sm:flex-row sm:justify-end"><button disabled={!!busy} onClick={()=>decision(false)} className="rounded-lg border border-[#F3C9BD] px-4 py-2.5 text-sm font-semibold text-[#B7472D] disabled:opacity-50">{busy==='reject'?'Rejecting…':'Reject application'}</button><button disabled={!!busy||!reviewComplete} onClick={()=>decision(true)} title={!ready?'Both required documents must be available first.':!reviewComplete?'Open both required documents before approval.':undefined} className="rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy==='approve'?'Approving…':'Approve verification'}</button></div>
  </div>
 </aside></>;
}

function normaliseDocuments(detail:Json|null):ReviewDocument[]{if(!detail)return[];const root=asJson(detail.verification)??asJson(detail.data)??detail;const raw=root.documents??root.verification_documents??root.files;const source:unknown[]=Array.isArray(raw)?raw:raw&&typeof raw==='object'?Object.entries(raw as Json).map(([type,value])=>typeof value==='object'&&value?{type,...value as Json}:{type,url:value}):[];const direct=[{type:'cnic',label:'CNIC',id:root.cnic_document_id,url:root.cnic_url},{type:'professional_certificate',label:'Professional Work Certificate',id:root.professional_work_certificate_document_id??root.certificate_document_id,url:root.professional_work_certificate_url??root.certificate_url}].filter(item=>item.id||item.url);const merged=[...source,...direct];const seen=new Set<string>();return merged.map((value,index)=>{const item=asJson(value)??{};const type=String(item.type??item.document_type??item.kind??`document_${index+1}`).toLowerCase();const id=String(item.id??item.document_id??'');const url=String(item.file_url??item.url??item.download_url??'');const key=id||`${type}:${url}`;if(seen.has(key))return null;seen.add(key);return{id,type,label:String(item.label??item.name??documentLabel(type)),fileName:String(item.file_name??item.filename??''),status:String(item.status??'submitted').toLowerCase(),url}}).filter((item):item is ReviewDocument=>item!==null)}
function asJson(value:unknown):Json|null{return value&&typeof value==='object'&&!Array.isArray(value)?value as Json:null}
function documentLabel(type:string){if(isCnic(type))return'CNIC';if(isCertificate(type))return'Professional Work Certificate';return type.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function isCnic(type:string){return type.includes('cnic')||type.includes('identity')}
function isCertificate(type:string){return type.includes('certificate')||type.includes('skill')||type.includes('professional')}
function documentKey(document:ReviewDocument){return document.id||`${document.type}:${document.url}`}
function detailStatus(detail:Json|null,business:Business){const root=detail?(asJson(detail.verification)??asJson(detail.data)??detail):{};return String(root.status??root.verification_status??business.verification_status??(business.is_verified?'verified':'pending')).toLowerCase()}
function extractDocumentUrl(value:unknown){const candidate=typeof value==='string'?value:String(asJson(value)?.url??asJson(value)?.file_url??asJson(value)?.download_url??'');if(!candidate)return'';try{const url=new URL(candidate);return url.protocol==='https:'||url.protocol==='http:'?url.toString():''}catch{return''}}
function formatDate(value?:string|null){if(!value)return'Unknown date';const date=new Date(value);return Number.isNaN(date.valueOf())?'Unknown date':date.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
