'use client';
import { useEffect, useState } from 'react';
import { Eye, RotateCcw, Save } from 'lucide-react';
import { defaultHomepageContent, HomepageContent, homepageContentFromApi, homepageContentToApi, readHomepageContent, saveHomepageContent, saveHomepagePreview } from '../lib/homepage-content';
import { getApiErrorMessage, hireProApi } from '../lib/api';
import { DashboardCard } from './dashboard/ui';

export default function HomepageEditor(){
 const [content,setContent]=useState<HomepageContent>(defaultHomepageContent),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState<'publish'|'reset'|'preview'|''>(''),[error,setError]=useState('');
 useEffect(()=>{hireProApi.admin.homepageContent().then(value=>setContent(homepageContentFromApi(value))).catch(e=>{setContent(readHomepageContent());setError(getApiErrorMessage(e,'Unable to load the admin homepage content. Showing locally saved content.'))}).finally(()=>setLoading(false))},[]);
 const field=(key:keyof HomepageContent,value:string)=>setContent(current=>({...current,[key]:value}));
 const publish=async()=>{setBusy('publish');setError('');try{const published=homepageContentFromApi(await hireProApi.admin.publishHomepageContent(homepageContentToApi(content)));setContent(published);saveHomepageContent(published);setSaved(true);setTimeout(()=>setSaved(false),2500)}catch(e){setError(getApiErrorMessage(e,'Unable to publish homepage content.'))}finally{setBusy('')}};
 const reset=async()=>{if(!window.confirm('Reset all homepage content to the server defaults?'))return;setBusy('reset');setError('');try{const defaults=homepageContentFromApi(await hireProApi.admin.resetHomepageContent());setContent(defaults);saveHomepageContent(defaults);setSaved(false)}catch(e){setError(getApiErrorMessage(e,'Unable to reset homepage content.'))}finally{setBusy('')}};
 const preview=async()=>{setBusy('preview');setError('');try{const validated=homepageContentFromApi(await hireProApi.admin.previewHomepageContent(homepageContentToApi(content)));saveHomepagePreview(validated);window.open('/?preview=1','_blank','noopener,noreferrer')}catch(e){setError(getApiErrorMessage(e,'Unable to preview homepage content.'))}finally{setBusy('')}};
 return <div><header className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">Website content</p><h1 className="mt-2 font-sora text-3xl font-bold">Homepage management</h1><p className="mt-2 text-sm text-[#667085]">{loading?'Loading published homepage content…':'Edit homepage copy, control section visibility, and preview changes.'}</p></div><div className="flex gap-2"><button onClick={reset} disabled={loading||!!busy} className="flex items-center gap-2 rounded-lg border border-[#D8DCE4] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-60"><RotateCcw size={16}/>{busy==='reset'?'Resetting…':'Reset'}</button><button onClick={preview} disabled={loading||!!busy} className="flex items-center gap-2 rounded-lg border border-[#D8DCE4] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-60"><Eye size={16}/>{busy==='preview'?'Validating…':'Preview'}</button><button onClick={publish} disabled={loading||!!busy} className="flex items-center gap-2 rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Save size={16}/>{busy==='publish'?'Publishing…':saved?'Published':'Publish'}</button></div></header>{error&&<div role="alert" className="mb-6 rounded-lg border border-[#F0DDAE] bg-[#FFF5DF] p-4 text-sm text-[#946200]">{error}</div>}
 <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-6"><Panel title="Hero section"><Input label="Heading before highlight" value={content.heroTitle} onChange={v=>field('heroTitle',v)}/><Input label="Highlighted heading" value={content.heroAccent} onChange={v=>field('heroAccent',v)}/><Input label="Heading suffix" value={content.heroSuffix} onChange={v=>field('heroSuffix',v)}/><Area label="Description" value={content.heroDescription} onChange={v=>field('heroDescription',v)}/><Input label="Popular searches (comma separated)" value={content.popularSearches.join(', ')} onChange={v=>setContent({...content,popularSearches:v.split(',').map(x=>x.trim()).filter(Boolean)})}/></Panel>
 <Panel title="Section headings"><Input label="Categories" value={content.categoriesTitle} onChange={v=>field('categoriesTitle',v)}/><Input label="Featured businesses" value={content.featuredTitle} onChange={v=>field('featuredTitle',v)}/><Input label="How it works" value={content.processTitle} onChange={v=>field('processTitle',v)}/><Input label="Testimonials" value={content.testimonialsTitle} onChange={v=>field('testimonialsTitle',v)}/></Panel>
 <Panel title="Business call to action"><Input label="Heading" value={content.ctaTitle} onChange={v=>field('ctaTitle',v)}/><Area label="Description" value={content.ctaDescription} onChange={v=>field('ctaDescription',v)}/><Input label="Button label" value={content.ctaButton} onChange={v=>field('ctaButton',v)}/><Input label="Button URL" value={content.ctaButtonUrl} onChange={v=>field('ctaButtonUrl',v)}/></Panel>
 <Panel title="Footer"><Area label="Company description" value={content.footerDescription} onChange={v=>field('footerDescription',v)}/></Panel></div>
 <div className="space-y-6"><Panel title="Section visibility">{Object.entries(content.sections).map(([key,value])=><label key={key} className="flex items-center justify-between rounded-lg border border-[#EAECF0] px-3 py-3"><span className="text-sm font-semibold capitalize">{key}</span><input type="checkbox" checked={value} onChange={e=>setContent({...content,sections:{...content.sections,[key]:e.target.checked}})} className="size-4 accent-[#0F9D8C]"/></label>)}</Panel><Panel title="Search appearance"><Input label="SEO title" value={content.seoTitle} onChange={v=>field('seoTitle',v)}/><Area label="Meta description" value={content.seoDescription} onChange={v=>field('seoDescription',v)}/></Panel><DashboardCard className="rounded-xl border border-[#BDE7DF] bg-[#F0FBF8] p-5"><p className="text-sm font-semibold text-[#126B5E]">Backend publishing connected</p><p className="mt-2 text-xs leading-5 text-[#39776E]">Publish saves changes globally. Preview validates without publishing, and Reset restores the server defaults.</p></DashboardCard></div></div></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <DashboardCard className="rounded-xl p-5"><h2 className="font-sora text-lg font-bold">{title}</h2><div className="mt-5 space-y-4">{children}</div></DashboardCard>}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#475467]">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-[#D8DCE4] px-3 py-2.5 text-sm outline-none focus:border-[#0F9D8C]"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#475467]">{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} className="w-full resize-y rounded-lg border border-[#D8DCE4] px-3 py-2.5 text-sm outline-none focus:border-[#0F9D8C]"/></label>}
