'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { ArrowRight, Banknote, Bell, Bookmark, BriefcaseBusiness, Building2, CheckCircle2, ChevronRight, CircleDollarSign, CircleHelp, ClipboardList, Clock3, Heart, LayoutDashboard, LogOut, Mail, MapPin, Menu, MessageSquareText, Plus, Rocket, Search, Settings, Sparkles, Star, UserRound, X } from 'lucide-react';
import { ApiError, Business, Category, getApiErrorMessage, hireProApi, hydrateApiToken, Notification, Onboarding, Quote, ROLE_STORAGE_KEY, TOKEN_STORAGE_KEY, User } from '../lib/api';
import { DashboardCard } from './dashboard/ui';
import AccountModal from './AccountModal';
import NotificationPopover from './NotificationPopover';

type Recommendation={business:Business;category:string;rating:number;reviewCount:number};
type Data = { user: User|null; quotes: Quote[]; notifications: Notification[]; favorites: Business[]; onboarding: Onboarding|null; recommendations:Recommendation[]; ownedBusinesses:Business[] };
function normalizeQuotes(records:Record<string,unknown>[]):Quote[]{return records.map(record=>({id:String(record.id??''),business_id:String(record.business_id??record.provider_id??''),details:String(record.details??record.description??record.title??'Service request'),budget:typeof record.budget==='number'?record.budget:typeof record.budget_max==='number'?record.budget_max:null,status:String(record.status??'open'),created_at:String(record.created_at??new Date().toISOString())}))}
function normalizeNotifications(records:Record<string,unknown>[]):Notification[]{return records.map(record=>({id:String(record.id??''),title:String(record.title??record.type??'HirePro update'),message:String(record.message??record.body??''),is_read:Boolean(record.is_read),created_at:String(record.created_at??new Date().toISOString())}))}

export default function RoleDashboard({ role }: { role: 'customer'|'business' }) {
  const router=useRouter(), provider=role==='business';
  const pathname=usePathname();
  const [data,setData]=useState<Data>({user:null,quotes:[],notifications:[],favorites:[],onboarding:null,recommendations:[],ownedBusinesses:[]});
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [menuOpen,setMenuOpen]=useState(false), [accountOpen,setAccountOpen]=useState(false), [notificationsOpen,setNotificationsOpen]=useState(false);
  useEffect(() => {
    let cancelled = false;
    const loginPath = `/${provider ? 'provider' : 'customer'}/login?next=${encodeURIComponent(pathname)}`;
    const optional = async <T,>(request: Promise<T>, fallback: T): Promise<T> => {
      try {
        return await request;
      } catch (error) {
        if (error instanceof ApiError && (error.status === 401 || error.status === 403)) throw error;
        return fallback;
      }
    };
    const recommendations = async (): Promise<Recommendation[]> => {
      if (provider) return [];
      const [businesses, categories] = await Promise.all([
        optional(hireProApi.businesses.list({ verified: true, limit: 6 }), []),
        optional(hireProApi.categories.list(), []),
      ]);
      const names = new Map(categories.map((category: Category) => [category.id, category.name]));
      return Promise.all(businesses.map(async business => {
        const reviews = await hireProApi.businesses.reviews(business.id).catch(() => []);
        return {
          business,
          category: names.get(business.category_id) ?? 'Local service',
          rating: reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0,
          reviewCount: reviews.length,
        };
      }));
    };
    const load = async () => {
      setLoading(true);
      setError('');
      if (!localStorage.getItem(TOKEN_STORAGE_KEY)) {
        router.replace(loginPath);
        return;
      }
      hydrateApiToken();
      const user = await hireProApi.auth.me();
      if (user.is_admin) {
        router.replace('/admin/dashboard');
        return;
      }
      if (user.role !== role) {
        router.replace(user.role === 'business' ? '/provider/dashboard' : '/customer/dashboard');
        return;
      }
      if (!cancelled) setData(current => ({ ...current, user }));

      const [dashboard, quoteRecords, notificationRecords, favoriteRecords, recommended, businessRecord] = await Promise.all([
        provider ? optional(hireProApi.provider.dashboard(), {}) : optional(hireProApi.customer.dashboard(), {}),
        provider ? optional(hireProApi.provider.requests(), []) : optional(hireProApi.customer.requests(), []),
        provider ? optional(hireProApi.provider.notifications(), []) : optional(hireProApi.customer.notifications(), []),
        provider ? Promise.resolve([]) : optional(hireProApi.customer.favorites(), []),
        recommendations(),
        provider ? optional(hireProApi.provider.business(), {}) : Promise.resolve({}),
      ]);
      const notificationSource = notificationRecords;
      const completionValue = provider && typeof dashboard.profile_completion === 'object' && dashboard.profile_completion
        ? Number((dashboard.profile_completion as Record<string, unknown>).percentage ?? 20)
        : 20;
      const onboarding = provider ? {
        user_id: user.id,
        current_step: Math.max(1, Math.ceil(completionValue / 20)),
        data: {},
        completed: completionValue >= 100,
      } satisfies Onboarding : null;
      const business = businessRecord as Partial<Business>;
      if (!cancelled) {
        setData({
          user,
          quotes: normalizeQuotes(quoteRecords),
          notifications: normalizeNotifications(notificationSource as Record<string,unknown>[]),
          favorites: favoriteRecords as unknown as Business[],
          onboarding,
          recommendations: recommended,
          ownedBusinesses: provider && business.id ? [business as Business] : [],
        });
      }
    };
    load().catch(error => {
      if (cancelled) return;
      if (error instanceof ApiError && (error.status === 401 || error.status === 403)) {
        localStorage.removeItem(TOKEN_STORAGE_KEY);
        localStorage.removeItem(ROLE_STORAGE_KEY);
        hireProApi.setToken(null);
        router.replace(loginPath);
        return;
      }
      setError(getApiErrorMessage(error, 'Unable to load your workspace.'));
    }).finally(() => {
      if (!cancelled) setLoading(false);
    });
    return () => { cancelled = true; };
  }, [pathname, provider, role]);
  const logout=async()=>{await hireProApi.auth.logout().catch(()=>undefined);localStorage.removeItem(TOKEN_STORAGE_KEY);localStorage.removeItem(ROLE_STORAGE_KEY);hireProApi.setToken(null);router.replace(`/${provider?'provider':'customer'}/login`)};
  const readNotification=async(id:string)=>{try{if(provider)await hireProApi.provider.readNotification(id);else await hireProApi.customer.readNotification(id);setData(current=>({...current,notifications:current.notifications.map(item=>item.id===id?{...item,is_read:true}:item)}))}catch(e){setError(getApiErrorMessage(e,'Unable to update the notification.'))}};
  const readAllNotifications=async()=>{try{if(provider)await hireProApi.provider.readAllNotifications();else await hireProApi.customer.readAll();setData(current=>({...current,notifications:current.notifications.map(item=>({...item,is_read:true}))}))}catch(e){setError(getApiErrorMessage(e,'Unable to update notifications.'))}};
  const unread=data.notifications.filter(n=>!n.is_read).length, firstName=data.user?.full_name.split(' ')[0]??(provider?'Partner':'there'), completion=data.onboarding?.completed?100:Math.min(90,Math.max(20,(data.onboarding?.current_step??1)*20));
  return <main className="min-h-screen bg-[#F4F6FA] text-[#12122E] font-inter"><div className="flex min-h-screen">
    <aside className={`fixed inset-y-0 left-0 z-50 ${provider?'w-72':'w-80'} bg-[#171344] text-white transition-transform lg:translate-x-0 ${menuOpen?'translate-x-0':'-translate-x-full'}`}><div className="flex h-full flex-col px-6 py-7">
      <div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-4 font-sora text-2xl font-bold"><span className="grid size-11 place-items-center rounded-full bg-[#19C5A5]"><Building2 size={22}/></span><span>HirePro{!provider&&<small className="mt-1 block font-mono text-[11px] font-normal uppercase tracking-[.14em] text-white/65">Enterprise Portal</small>}</span></Link><button className="lg:hidden" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X/></button></div>
      {provider&&<div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-full bg-gradient-to-br from-[#0F9D8C] to-[#63D5C8] font-bold">{data.user?.full_name.charAt(0)??'H'}</div><div className="min-w-0"><p className="truncate font-semibold">{data.user?.full_name??'HirePro member'}</p><p className="text-xs text-white/55">Service provider</p></div></div></div>}
      <nav className="mt-10 space-y-2">{provider?<><Nav href="/provider/dashboard" pathname={pathname} icon={<LayoutDashboard size={19}/>} label="Overview"/><Nav href="/provider/quotes" pathname={pathname} icon={<MessageSquareText size={19}/>} label="Quote Requests"/><Nav href="/provider/profile" pathname={pathname} icon={<UserRound size={19}/>} label="Business Profile"/><Nav href="/provider/insights" pathname={pathname} icon={<Star size={19}/>} label="Insights"/><Nav href="/provider/settings" pathname={pathname} icon={<Settings size={19}/>} label="Settings"/></>:<><Nav href="/customer/dashboard" pathname={pathname} icon={<LayoutDashboard size={19}/>} label="Overview"/><Nav href="/customer/find" pathname={pathname} icon={<Search size={19}/>} label="Find Pros"/><Nav href="/customer/requests" pathname={pathname} icon={<ClipboardList size={19}/>} label="My Requests"/><Nav href="/customer/saved" pathname={pathname} icon={<Bookmark size={19}/>} label="Saved"/><Nav href="/customer/settings" pathname={pathname} icon={<Settings size={19}/>} label="Settings"/></>}</nav>
      <div className="mt-auto">{!provider&&<><Link href="/customer/requests" className="mb-6 flex items-center justify-center gap-2 rounded-lg bg-[#20C5A6] px-4 py-3.5 text-sm font-semibold"><Plus size={17}/>Post a Request</Link><Link href="/contact" className="mb-5 flex items-center gap-3 px-4 text-sm text-white/65 hover:text-white"><CircleHelp size={19}/>Help Center</Link></>}<button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/65 transition hover:bg-white/10 hover:text-white"><LogOut size={18}/>Sign out</button></div>
    </div></aside>
    <div className={`min-w-0 flex-1 ${provider?'lg:pl-72':'lg:pl-80'}`}><header className="sticky top-0 z-30 border-b border-[#DDE2E7] bg-[#F8FAFB]/95 backdrop-blur-xl"><div className="flex h-[92px] items-center gap-5 px-5 md:px-8 lg:px-11"><button className="lg:hidden" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu/></button><div className="relative hidden max-w-xl flex-1 md:block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#263A37]" size={20}/><input className="w-full rounded-lg border border-[#C9D0D1] bg-[#E4E8E9] py-3.5 pl-12 pr-4 text-sm outline-none focus:border-[#0F9D8C] focus:bg-white" placeholder={provider?'Search requests, customers…':'Search professionals, requests…'}/></div><div className="ml-auto flex items-center gap-4"><Link href={provider?'/provider/quotes':'/customer/requests'} className="hidden text-[#17342F] sm:block" aria-label="Messages"><Mail size={21}/></Link><div className="relative"><button onClick={()=>setNotificationsOpen(value=>!value)} className="relative grid size-9 place-items-center text-[#17342F]" aria-label="Open notifications" aria-expanded={notificationsOpen}><Bell size={21}/>{unread>0&&<span className="absolute right-1 top-0 size-2 rounded-full bg-[#F4623A]"/>}</button><NotificationPopover open={notificationsOpen} notifications={data.notifications} onClose={()=>setNotificationsOpen(false)} onRead={readNotification} onReadAll={readAllNotifications}/></div>{!provider&&<><Link href="/contact" className="hidden rounded-lg border border-[#AFC3BD] px-5 py-2.5 text-sm font-semibold md:block">Support</Link><Link href="/customer/requests" className="rounded-lg bg-[#19BFA0] px-5 py-2.5 text-sm font-semibold text-white">Create Request</Link></>}<button onClick={()=>setAccountOpen(true)} className="grid size-11 place-items-center overflow-hidden rounded-full border-2 border-[#152A26] bg-[#1E1B6E] font-bold text-white" aria-label="Open account profile">{String((data.user as (User&{avatar?:string})|null)?.avatar??'')?<img src={String((data.user as User&{avatar?:string}).avatar)} alt="" className="h-full w-full object-cover"/>:data.user?.full_name.charAt(0)??'H'}</button></div></div></header>
      <div className="p-5 md:p-8 lg:p-10">{error&&<div role="alert" className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{loading?<Skeleton/>:provider?<ProviderRouteContent pathname={pathname} data={data} firstName={firstName} unread={unread}/>:<CustomerRouteContent pathname={pathname} data={data} firstName={firstName} unread={unread}/>}</div>
    </div>
  </div>{menuOpen&&<button className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={()=>setMenuOpen(false)} aria-label="Close navigation"/>}<AccountModal open={accountOpen} role={role} user={data.user} onClose={()=>setAccountOpen(false)} onUserUpdated={user=>setData(current=>({...current,user}))}/></main>
}
function CustomerRouteContent({pathname,data,firstName,unread}:{pathname:string;data:Data;firstName:string;unread:number}){if(pathname==='/customer/find')return <CustomerFind data={data}/>;if(pathname==='/customer/requests')return <CustomerRequests quotes={data.quotes}/>;if(pathname==='/customer/saved')return <CustomerSaved businesses={data.favorites}/>;if(pathname==='/customer/notifications')return <NotificationPage notifications={data.notifications} title="Your notifications" customer/>;if(pathname==='/customer/settings')return <SettingsPage customer/>;return <CustomerReferenceContent data={data} firstName={firstName} unread={unread}/>}
function CustomerReferenceContent({data,firstName,unread}:{data:Data;firstName:string;unread:number}){const active=data.quotes.filter(q=>q.status!=='closed'),budget=data.quotes.reduce((sum,q)=>sum+(q.budget??0),0),priority=active[0]??data.quotes[0];return <div className="space-y-9">
 <section className="relative overflow-hidden rounded-[14px] border border-[#171456] bg-gradient-to-r from-[#2C2379] to-[#263F7A] px-7 py-12 text-white md:px-12 md:py-16"><div className="relative z-10 max-w-3xl"><h1 className="font-sora text-3xl font-bold leading-tight tracking-[-.03em] md:text-5xl">The right professional is three simple steps away.</h1><p className="mt-7 max-w-3xl text-base leading-7 text-white/80 md:text-lg">Welcome, {firstName}. Post exactly what you need, compare vetted local professionals, and let the right talent come to you.</p></div><div className="absolute -right-8 top-1/2 hidden h-36 w-72 -translate-y-1/2 opacity-35 lg:block"><svg viewBox="0 0 280 130" className="h-full w-full"><g stroke="#7EDDD1" strokeWidth="1" fill="none">{[[20,80,90,20],[20,80,130,105],[90,20,170,60],[130,105,170,60],[170,60,250,25],[170,60,245,105],[90,20,130,105],[20,80,170,60]].map((p,i)=><line key={i} x1={p[0]} y1={p[1]} x2={p[2]} y2={p[3]}/>)}</g>{[[20,80],[90,20],[130,105],[170,60],[250,25],[245,105]].map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="4" fill="#7EDDD1"/>)}</svg></div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReferenceStat icon={<ClipboardList/>} label="Active Requests" value={active.length.toString()} tone="teal"/><ReferenceStat icon={<UserRound/>} label="Pros Contacted" value={new Set(data.quotes.map(q=>q.business_id)).size.toString()} tone="indigo"/><ReferenceStat icon={<Bookmark/>} label="Saved Profiles" value={data.favorites.length.toString()} tone="indigo"/><ReferenceStat icon={<Banknote/>} label="Total Budgets" value={budget?`PKR ${compactNumber(budget)}`:'—'} tone="teal"/></section>
 <section className="grid gap-7 xl:grid-cols-[1fr_328px]"><DashboardCard className="overflow-hidden rounded-xl"><div className="flex items-center justify-between border-b border-[#E4E7EC] px-7 py-5"><h2 className="font-sora text-2xl font-bold">Recent Activity</h2><Link href="/customer/requests" className="text-sm font-semibold text-[#087766]">View All</Link></div><div className="divide-y divide-[#E8EAF0]">{data.notifications.slice(0,3).map(n=><ActivityRow key={n.id} title={n.title} copy={n.message} date={n.created_at}/>)}{data.notifications.length===0&&data.quotes.slice(0,3).map(q=><ActivityRow key={q.id} title="Request submitted" copy={q.details} date={q.created_at}/>)}{data.notifications.length===0&&data.quotes.length===0&&<div className="p-10 text-center"><p className="font-semibold">No recent activity</p><p className="mt-1 text-sm text-[#7B8492]">Create your first request to get started.</p></div>}</div></DashboardCard>
 {priority?<section className="rounded-xl bg-gradient-to-br from-[#2A2177] to-[#33247F] p-7 text-white shadow-md"><span className="grid size-12 place-items-center rounded-xl bg-white/15"><Rocket/></span><h2 className="mt-4 font-sora text-xl font-bold">High-Priority Request</h2><p className="mt-6 text-xs text-white/60">Project</p><p className="mt-2 line-clamp-3 font-semibold leading-6">{priority.details}</p><div className="mt-6 flex justify-between text-sm"><span>Sourcing Progress</span><span className="font-bold text-[#27D0AE]">{priority.status==='closed'?'100%':'75%'}</span></div><div className="mt-2 h-2 rounded-full bg-white/20"><div className="h-full w-3/4 rounded-full bg-[#20C5A6]"/></div><div className="mt-5 space-y-2 text-sm"><p className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#27D0AE]"/>Request Posted</p><p className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#27D0AE]"/>Professionals Notified</p><p className="flex items-center gap-2 text-white/60"><span className="size-3.5 rounded-full border border-white/60"/>Final Selection</p></div><Link href="/customer/requests" className="mt-6 block rounded-lg bg-white/15 py-3 text-center text-sm font-semibold">Manage Request</Link></section>:<section className="grid min-h-72 place-items-center rounded-xl bg-[#2A2177] p-7 text-center text-white"><div><Rocket className="mx-auto text-[#27D0AE]"/><h2 className="mt-4 font-sora text-xl font-bold">Your priority request</h2><p className="mt-2 text-sm text-white/60">Post a request and track its progress here.</p><Link href="/customer/requests" className="mt-5 inline-flex rounded-lg bg-[#20C5A6] px-4 py-2.5 text-sm font-semibold">Create Request</Link></div></section>}</section>
 <section><h2 className="mb-5 font-sora text-2xl font-bold">Recommended Professionals</h2>{data.recommendations.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.recommendations.slice(0,3).map(item=><ReferenceProfessional key={item.business.id} item={item}/>)}</div>:<DashboardCard className="rounded-xl p-8 text-center"><p className="text-sm text-[#667085]">No verified professionals are available yet.</p></DashboardCard>}</section>
 </div>}
function compactNumber(value:number){return value>=1000000?`${(value/1000000).toFixed(1)}m`:value>=1000?`${(value/1000).toFixed(1)}k`:value.toLocaleString()}
function ReferenceStat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string;tone:'teal'|'indigo'}){return <DashboardCard className="rounded-xl px-7 py-7"><div className="flex items-center gap-5"><span className={`grid size-14 place-items-center rounded-xl ${tone==='teal'?'bg-[#D4F4EC] text-[#08AA8A]':'bg-[#EEECFF] text-[#4A47B5]'}`}>{icon}</span><div><p className="font-mono text-xs uppercase tracking-[.09em] text-[#26352F]">{label}</p><p className="mt-1 font-sora text-3xl font-bold tabular-nums">{value}</p></div></div></DashboardCard>}
function ActivityRow({title,copy,date}:{title:string;copy:string;date:string}){return <div className="flex gap-4 px-7 py-5"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#E4E8EA] text-[#25423D]"><MessageSquareText size={19}/></span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-[#45504D]">{copy}</p><p className="mt-2 font-mono text-xs text-[#7D8583]">{new Date(date).toLocaleString()}</p></div></div>}
function ReferenceProfessional({item}:{item:Recommendation}){const b=item.business,initials=b.name.split(' ').slice(0,2).map(v=>v.charAt(0)).join('');return <DashboardCard interactive className="rounded-xl p-7 text-center"><span className="mx-auto grid size-24 place-items-center rounded-full bg-[#D4F4EC] text-lg font-semibold text-[#075E51]">{initials}</span><h3 className="mt-5 font-sora text-lg font-bold">{b.name}</h3><p className="mt-1 text-sm text-[#45504D]">{item.category}</p><p className="mt-5 flex items-center justify-center gap-2 text-sm"><Star size={16} className="text-[#F59E0B]"/>{item.reviewCount?item.rating.toFixed(1):'New'} <span className="text-[#45504D]">({item.reviewCount} reviews)</span></p><Link href={`/businesses/${b.id}`} className="mt-5 block rounded-lg border border-[#AFC3BD] py-2.5 text-sm font-semibold">View Profile</Link></DashboardCard>}
function ProviderRouteContent({pathname,data,firstName,unread}:{pathname:string;data:Data;firstName:string;unread:number}){if(pathname==='/provider/quotes')return <ProviderQuotes quotes={data.quotes} completion={providerCompletion(data)}/>;if(pathname==='/provider/profile')return <ProviderProfile data={data}/>;if(pathname==='/provider/insights')return <ProviderInsights data={data}/>;if(pathname==='/provider/notifications')return <NotificationPage notifications={data.notifications} title="Provider notifications"/>;if(pathname==='/provider/settings')return <SettingsPage/>;return <ProviderContent data={data} firstName={firstName} unread={unread}/>}
function PageTitle({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode}){return <header className="mb-8 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">{eyebrow}</p><h1 className="mt-2 font-sora text-3xl font-bold tracking-[-.03em] md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#667085]">{copy}</p></div>{action}</header>}
function CustomerFind({data}:{data:Data}){return <div><PageTitle eyebrow="Discover" title="Find a professional" copy="Browse verified local specialists, compare real customer reviews, and build a shortlist for your next project." action={<Link href="/businesses" className="rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold text-white">Open advanced search</Link>}/><DashboardCard className="mb-8 rounded-[18px] p-5"><div className="grid gap-3 md:grid-cols-[1fr_.7fr_auto]"><label className="relative"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input className="w-full rounded-lg border border-[#D8DCE4] py-3 pl-10 pr-4 text-sm" placeholder="What service do you need?"/></label><label className="relative"><MapPin size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#98A0AF]"/><input className="w-full rounded-lg border border-[#D8DCE4] py-3 pl-10 pr-4 text-sm" placeholder="City or area"/></label><Link href="/businesses" className="grid place-items-center rounded-lg bg-[#1E1B6E] px-5 text-sm font-semibold text-white">Search</Link></div></DashboardCard><h2 className="mb-4 font-sora text-xl font-bold">Recommended professionals</h2>{data.recommendations.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.recommendations.map(item=><ProfessionalCard key={item.business.id} item={item}/>)}</div>:<CustomerEmpty kind="saved"/>}</div>}
function CustomerRequests({quotes}:{quotes:Quote[]}){return <div><PageTitle eyebrow="Projects" title="My requests" copy="Follow every request from first quote to final decision. New provider replies and status changes appear here." action={<Link href="/businesses" className="rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold text-white">New request</Link>}/><Panel title="All requests" subtitle={`${quotes.length} total requests`} action="Filter">{quotes.length?<div className="divide-y divide-[#EEF0F4]">{quotes.map(q=><QuoteRow key={q.id} quote={q}/>)}</div>:<CustomerEmpty kind="requests"/>}</Panel></div>}
function CustomerSaved({businesses}:{businesses:Business[]}){return <div><PageTitle eyebrow="Shortlist" title="Saved professionals" copy="Keep trusted providers together, revisit their profiles, and compare your strongest options." action={<Link href="/businesses" className="rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold text-white">Discover more</Link>}/>{businesses.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{businesses.map(b=><Link key={b.id} href={`/businesses/${b.id}`}><DashboardCard interactive className="rounded-xl p-5"><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#1E1B6E] font-bold text-white">{b.name.charAt(0)}</span><div className="min-w-0 flex-1"><p className="truncate font-sora font-bold">{b.name}</p><p className="mt-1 text-xs text-[#8A91A1]">{b.city} · {b.is_verified?'Verified':'Not verified'}</p></div><Heart size={18} fill="currentColor" className="text-[#F4623A]"/></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-[#667085]">{b.description}</p></DashboardCard></Link>)}</div>:<CustomerEmpty kind="saved"/>}</div>}
function NotificationPage({notifications,title,customer=false}:{notifications:Notification[];title:string;customer?:boolean}){const [items,setItems]=useState(notifications),[busy,setBusy]=useState('');useEffect(()=>setItems(notifications),[notifications]);const read=async(id:string)=>{if(!customer)return;setBusy(id);try{await hireProApi.customer.readNotification(id);setItems(current=>current.map(item=>item.id===id?{...item,is_read:true}:item))}finally{setBusy('')}};const readAll=async()=>{if(!customer)return;setBusy('all');try{await hireProApi.customer.readAll();setItems(current=>current.map(item=>({...item,is_read:true})))}finally{setBusy('')}};return <div><PageTitle eyebrow="Inbox" title={title} copy="Stay current with replies, quote activity, reminders, and important account updates." action={customer&&items.some(item=>!item.is_read)?<button disabled={busy==='all'} onClick={readAll} className="rounded-lg border border-[#D8DCE4] bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-60">{busy==='all'?'Updating…':'Mark all as read'}</button>:undefined}/><DashboardCard className="overflow-hidden rounded-xl">{items.length?<div className="divide-y divide-[#EEF0F4]">{items.map(n=><button type="button" disabled={!customer||n.is_read||busy===n.id} onClick={()=>read(n.id)} key={n.id} className={`flex w-full gap-4 p-5 text-left ${n.is_read?'bg-white':'bg-[#F4FBF9]'} disabled:cursor-default`}><span className={`mt-1 size-2 shrink-0 rounded-full ${n.is_read?'bg-[#C8CDD6]':'bg-[#0F9D8C]'}`}/><span><span className="block font-semibold">{n.title}</span><span className="mt-1 block text-sm leading-6 text-[#667085]">{n.message}</span><span className="mt-2 block text-xs text-[#9CA3AF]">{new Date(n.created_at).toLocaleString()}</span></span></button>)}</div>:<div className="py-20 text-center"><Bell className="mx-auto text-[#AAB1BD]"/><p className="mt-4 font-semibold">You&apos;re all caught up</p><p className="mt-1 text-sm text-[#8A91A1]">New updates will appear here.</p></div>}</DashboardCard></div>}
function SettingsPage({customer=false}:{customer?:boolean}){const [email,setEmail]=useState(true),[push,setPush]=useState(true),[saved,setSaved]=useState(false),[loading,setLoading]=useState(customer),[error,setError]=useState('');useEffect(()=>{if(!customer)return;hireProApi.customer.preferences().then(value=>{if(typeof value.email_notifications==='boolean')setEmail(value.email_notifications);if(typeof value.push_notifications==='boolean')setPush(value.push_notifications)}).catch(e=>setError(getApiErrorMessage(e,'Unable to load preferences.'))).finally(()=>setLoading(false))},[customer]);const save=async()=>{if(!customer){setSaved(true);return}setLoading(true);setError('');try{await hireProApi.customer.updatePreferences({email_notifications:email,push_notifications:push});setSaved(true)}catch(e){setError(getApiErrorMessage(e,'Unable to save preferences.'))}finally{setLoading(false)}};return <div><PageTitle eyebrow="Account" title="Settings" copy="Manage how HirePro communicates with you and personalize your workspace."/><div className="grid gap-7 xl:grid-cols-[1fr_.7fr]"><DashboardCard className="rounded-xl p-6"><h2 className="font-sora text-lg font-bold">Notification preferences</h2>{error&&<p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 space-y-5"><Toggle label="Email notifications" copy="Receive quote and account updates by email." on={email} setOn={setEmail}/><Toggle label="Push notifications" copy="Get time-sensitive activity on your device." on={push} setOn={setPush}/></div><button disabled={loading} onClick={save} className="mt-7 rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{loading?'Saving…':'Save preferences'}</button>{saved&&<p className="mt-3 text-sm text-[#237A4B]">Preferences saved.</p>}</DashboardCard><DashboardCard className="rounded-xl p-6"><h2 className="font-sora text-lg font-bold">Appearance</h2><p className="mt-2 text-sm text-[#667085]">Theme preferences follow your HirePro account settings.</p></DashboardCard></div></div>}
function Toggle({label,copy,on,setOn}:{label:string;copy:string;on:boolean;setOn:(value:boolean)=>void}){return <button onClick={()=>setOn(!on)} className="flex w-full items-center gap-4 text-left"><span className={`relative h-6 w-11 rounded-full transition ${on?'bg-[#0F9D8C]':'bg-[#D0D5DD]'}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${on?'left-6':'left-1'}`}/></span><span><span className="block text-sm font-semibold">{label}</span><span className="mt-0.5 block text-xs text-[#8A91A1]">{copy}</span></span></button>}
function providerCompletion(data:Data){const b=data.ownedBusinesses[0],o=data.onboarding?.data??{};return [!!(b?.name&&b.description&&b.city),Array.isArray(o.photos)&&o.photos.length>0,Array.isArray(o.services)&&o.services.length>0,b?.is_verified??false,!!o.pricing].filter(Boolean).length*20}
function ProviderQuotes({quotes,completion}:{quotes:Quote[];completion:number}){return <div><PageTitle eyebrow="Lead inbox" title="Quote requests" copy="Review customer opportunities by urgency and keep your response pipeline moving."/><Panel title="All quote requests" subtitle="Newest and most time-sensitive first" action={`${quotes.length} total`}>{quotes.length?<div className="divide-y divide-[#EEF0F4]">{[...quotes].sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at)).map(q=><ProviderQuote key={q.id} quote={q}/>)}</div>:<ProviderQuoteEmpty completion={completion}/>}</Panel></div>}
function ProviderProfile({data}:{data:Data}){const b=data.ownedBusinesses[0],completion=providerCompletion(data);return <div><PageTitle eyebrow="Listing" title="Business profile" copy="Manage the details customers use to discover, evaluate, and trust your business." action={b?<Link href={`/businesses/${b.id}`} className="rounded-xl bg-[#1E1B6E] px-5 py-3 text-sm font-semibold text-white">View public profile</Link>:undefined}/>{b?<div className="grid gap-7 xl:grid-cols-[1fr_.7fr]"><DashboardCard className="rounded-xl p-6"><div className="flex items-start gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-[#1E1B6E] text-2xl font-bold text-white">{b.name.charAt(0)}</span><div><h2 className="font-sora text-xl font-bold">{b.name}</h2><p className="mt-1 text-sm text-[#667085]">{b.city} · {b.address}</p><p className="mt-2 text-xs font-semibold text-[#0F9D8C]">{b.is_verified?'Verified business':'Verification pending'}</p></div></div><p className="mt-6 text-sm leading-7 text-[#667085]">{b.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Phone" value={b.phone||'Not added'}/><Info label="Website" value={b.website||'Not added'}/><Info label="Profile views" value={b.view_count.toLocaleString()}/><Info label="Status" value={b.is_active?'Active':'Inactive'}/></div></DashboardCard><DashboardCard className="rounded-xl p-6"><ProgressRing value={completion}/><h3 className="mt-5 font-sora text-lg font-bold">Profile completion</h3><p className="mt-2 text-sm leading-6 text-[#667085]">Add services, pricing, photos, and credentials through onboarding to improve customer confidence.</p><Link href="/provider/profile/setup" className="mt-5 inline-flex rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-sm font-semibold text-white">Manage listing</Link></DashboardCard></div>:<ProviderProfileEmpty/>}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#F7F8FA] p-3"><p className="text-xs text-[#8A91A1]">{label}</p><p className="mt-1 truncate text-sm font-semibold">{value}</p></div>}
function ProviderInsights({data}:{data:Data}){const views=data.ownedBusinesses.reduce((s,b)=>s+b.view_count,0),conversion=views?Math.min(100,data.quotes.length/views*100):0;return <div><PageTitle eyebrow="Performance" title="Insights" copy="Understand whether your listing is attracting attention and converting views into customer requests."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<UserRound/>} label="Profile views" value={views} note="Live total" color="indigo"/><Metric icon={<MessageSquareText/>} label="Quote requests" value={data.quotes.length} note="All time" color="teal"/><Metric icon={<CheckCircle2/>} label="View → quote" value={`${conversion.toFixed(1)}%`} note="Calculated conversion" color="green"/><Metric icon={<Clock3/>} label="Response time" value="—" note="Backend event needed" color="coral"/></div><DashboardCard className="mt-7 rounded-xl p-6"><h2 className="font-sora text-lg font-bold">Conversion funnel</h2><p className="mt-1 text-sm text-[#667085]">From public profile views to quote requests.</p><div className="mt-8 space-y-5"><Funnel label="Profile views" value={views} width={100}/><Funnel label="Quote requests" value={data.quotes.length} width={views?Math.max(4,conversion):0}/></div></DashboardCard></div>}
function Funnel({label,value,width}:{label:string;value:number;width:number}){return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="tabular-nums text-[#667085]">{value}</span></div><div className="h-9 rounded-lg bg-[#EEF0F4]"><div className="grid h-full min-w-0 place-items-center rounded-lg bg-[#0F9D8C] text-xs font-semibold text-white transition-all" style={{width:`${width}%`}}>{width>15&&`${width.toFixed(1)}%`}</div></div></div>}
function ProviderContent({data,firstName,unread}:{data:Data;firstName:string;unread:number}){const business=data.ownedBusinesses[0],onboarding=data.onboarding?.data??{};const checks=[{label:'Basic info',done:!!(business?.name&&business.description&&business.city),href:'/provider/profile/setup'},{label:'Photos',done:Array.isArray(onboarding.photos)&&onboarding.photos.length>0,href:'/provider/profile/setup'},{label:'Services',done:Array.isArray(onboarding.services)&&onboarding.services.length>0,href:'/provider/profile/setup'},{label:'Verification',done:business?.is_verified??false,href:'/provider/profile/setup'},{label:'Pricing',done:!!onboarding.pricing,href:'/provider/profile/setup'}];const complete=checks.filter(c=>c.done).length*20,views=data.ownedBusinesses.reduce((sum,b)=>sum+b.view_count,0),conversion=views?Math.min(100,(data.quotes.length/views)*100):0,completeEnough=complete>=80;return <div className="space-y-8">
 <section className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#0F9D8C]">Provider workspace</p><h1 className="mt-2 font-sora text-3xl font-bold tracking-[-.03em] md:text-4xl">Run your business, {firstName}.</h1><p className="mt-2 text-sm text-[#667085]">{completeEnough?'New opportunities are your priority today.':'Complete your profile to improve search visibility and customer trust.'}</p></div><Link href={business?`/businesses/${business.id}`:'/provider/profile/setup'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold text-white">{business?'View public profile':'Create business profile'}<ArrowRight size={16}/></Link></section>
 <div className="grid gap-7 xl:grid-cols-[.9fr_1.1fr]"><DashboardCard className="rounded-[18px] p-6"><div className="flex items-center gap-5"><ProgressRing value={complete}/><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#8A91A1]">Profile strength</p><p className="mt-1 font-sora text-2xl font-bold">{complete}% complete</p><p className="mt-2 text-xs leading-5 text-[#667085]">Complete profiles are easier for customers to trust and compare.</p></div></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{checks.map(step=><Link key={step.label} href={step.href} className="flex items-center gap-2 rounded-lg border border-[#E8EAF0] px-3 py-2.5 text-xs font-semibold hover:bg-[#F8F9FB]"><span className={`grid size-5 place-items-center rounded-full ${step.done?'bg-[#E9F5EE] text-[#237A4B]':'bg-[#F2F4F7] text-[#98A0AF]'}`}>{step.done?<CheckCircle2 size={13}/>:<span className="size-1.5 rounded-full bg-current"/>}</span>{step.label}<ChevronRight size={13} className="ml-auto text-[#AAB1BD]"/></Link>)}</div></DashboardCard>
 <DashboardCard className="rounded-[18px] p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#8A91A1]">Listing performance</p><h2 className="mt-1 font-sora text-xl font-bold">Is your profile working?</h2></div><Star size={20} className="text-[#FFB800]"/></div><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><Insight value={views.toLocaleString()} label="Profile views"/><Insight value={data.quotes.length.toString()} label="Quote requests"/><Insight value={`${conversion.toFixed(1)}%`} label="View → quote"/><Insight value="—" label="Response time"/></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs"><span className="text-[#667085]">View-to-quote conversion</span><span className="font-semibold tabular-nums">{conversion.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-[#EEF0F4]"><div className="h-full rounded-full bg-[#0F9D8C] transition-all" style={{width:`${conversion}%`}}/></div></div><p className="mt-4 text-xs text-[#8A91A1]">Response-time and win-rate tracking require provider response events from the backend.</p></DashboardCard></div>
 {completeEnough&&views>0&&data.quotes.length===0&&<section className="flex flex-col gap-4 rounded-[18px] border border-[#D7D4F1] bg-[#F3F1FF] p-6 md:flex-row md:items-center"><Sparkles className="text-[#4A47C4]"/><div className="flex-1"><p className="font-sora font-bold">You&apos;re visible—now turn views into leads</p><p className="mt-1 text-sm text-[#667085]">Pro placement can help a complete profile stand out in competitive categories.</p></div><button className="rounded-lg bg-[#1E1B6E] px-4 py-2.5 text-sm font-semibold text-white">Explore Pro</button></section>}
 <div className="grid gap-7 xl:grid-cols-[1.45fr_.75fr]"><Panel title="Quote request inbox" subtitle="Newest opportunities appear first" action={`${data.quotes.length} total`}>{data.quotes.length?<div className="divide-y divide-[#EEF0F4]">{[...data.quotes].sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at)).slice(0,6).map(q=><ProviderQuote key={q.id} quote={q}/>)}</div>:<ProviderQuoteEmpty completion={complete}/>}</Panel><div className="space-y-7"><Panel title="Business profile" subtitle="What customers can see" action="Manage">{business?<div className="p-2"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-xl bg-[#1E1B6E] font-bold text-white">{business.name.charAt(0)}</span><div><p className="font-semibold">{business.name}</p><p className="text-xs text-[#8A91A1]">{business.city} · {business.is_verified?'Verified':'Verification pending'}</p></div></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-[#667085]">{business.description}</p><Link href={`/businesses/${business.id}`} className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#0F9D8C]">Open profile <ArrowRight size={14}/></Link></div>:<ProviderProfileEmpty/>}</Panel><Panel title="Notifications" subtitle={`${unread} unread`} action="View all">{data.notifications.length?data.notifications.slice(0,3).map(n=><Notice key={n.id} note={n}/>):<p className="py-7 text-center text-sm text-[#8A91A1]">You&apos;re all caught up.</p>}</Panel></div></div>
 </div>}
function ProgressRing({value}:{value:number}){return <div className="relative grid size-24 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#0F9D8C ${value*3.6}deg,#E8EAF0 0)`}}><div className="grid size-[74px] place-items-center rounded-full bg-white"><span className="font-sora text-xl font-bold tabular-nums">{value}%</span></div></div>}
function Insight({value,label}:{value:string;label:string}){return <div><p className="font-sora text-2xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-[#8A91A1]">{label}</p></div>}
function ProviderQuote({quote}:{quote:Quote}){const [busy,setBusy]=useState(''),[status,setStatus]=useState(quote.status);const hours=Math.max(0,(Date.now()-new Date(quote.created_at).getTime())/36e5),tone=hours<24?'bg-[#E9F5EE] text-[#237A4B]':hours<72?'bg-[#FFF5DF] text-[#946200]':'bg-[#FDEDE8] text-[#B7472D]',age=hours<1?'Just now':hours<24?`${Math.floor(hours)}h ago`:`${Math.floor(hours/24)}d ago`;const respond=async()=>{setBusy('respond');try{await hireProApi.provider.respond(quote.id,{message:'Available to discuss',amount:quote.budget});setStatus('responded')}finally{setBusy('')}};const decline=async()=>{setBusy('decline');try{await hireProApi.provider.decline(quote.id);setStatus('declined')}finally{setBusy('')}};return <div className="flex flex-col gap-3 px-2 py-4 sm:flex-row sm:items-center"><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-semibold ${tone}`}>{age}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{quote.details}</p><p className="mt-1 text-xs text-[#8A91A1]">{quote.budget!==null?`Budget PKR ${quote.budget.toLocaleString()}`:'Budget not provided'} · <span className="capitalize">{status}</span></p></div>{status!=='declined'&&status!=='responded'&&<div className="flex gap-2"><button disabled={!!busy} onClick={decline} className="rounded-lg border border-[#D8DCE4] px-3 py-2 text-xs font-semibold text-[#344054] disabled:opacity-60">{busy==='decline'?'Declining…':'Decline'}</button><button disabled={!!busy} onClick={respond} className="rounded-lg bg-[#0F9D8C] px-3 py-2 text-xs font-semibold text-white disabled:opacity-60">{busy==='respond'?'Sending…':'Respond'}</button></div>}</div>}
function ProviderQuoteEmpty({completion}:{completion:number}){return <div className="grid min-h-64 place-items-center p-6 text-center"><div><svg viewBox="0 0 160 95" className="mx-auto h-24 w-40" aria-hidden="true"><path d="M29 73h102" stroke="#D5D9E2" strokeWidth="2"/><rect x="41" y="18" width="78" height="58" rx="9" fill="#F4F6FA" stroke="#CDD2DC" strokeWidth="2"/><path d="M58 36h44M58 47h30" stroke="#A3AAB8" strokeWidth="3" strokeLinecap="round"/><circle cx="112" cy="68" r="15" fill="#E4F6F2"/><path d="M105 68h14M112 61v14" stroke="#0F9D8C" strokeWidth="2.5" strokeLinecap="round"/></svg><p className="mt-3 font-semibold">No quote requests yet</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-[#667085]">{completion<100?`Your profile is ${completion}% complete. Finish the remaining steps to improve how often customers discover and trust your listing.`:'Your profile is ready. New customer requests will appear here as soon as they arrive.'}</p>{completion<100&&<Link href="/provider/profile/setup" className="mt-4 inline-flex rounded-lg bg-[#0F9D8C] px-4 py-2.5 text-xs font-semibold text-white">Complete your profile</Link>}</div></div>}
function ProviderProfileEmpty(){return <div className="py-8 text-center"><BriefcaseBusiness className="mx-auto text-[#9CA3AF]"/><p className="mt-3 text-sm font-semibold">Create your business listing</p><p className="mt-1 text-xs text-[#8A91A1]">Add basic details before completing services and credentials.</p><Link href="/provider/profile/setup" className="mt-4 inline-flex rounded-lg bg-[#0F9D8C] px-4 py-2 text-xs font-semibold text-white">Get started</Link></div>}
function CustomerContent({data,firstName,unread}:{data:Data;firstName:string;unread:number}){const active=data.quotes.filter(q=>q.status!=='closed'),hasActivity=data.quotes.length>0||data.favorites.length>0;return <div className="space-y-8">
 {hasActivity&&data.quotes[0]?<DashboardCard interactive className="overflow-hidden rounded-[20px] p-6 md:p-8"><div className="flex flex-col gap-6 md:flex-row md:items-center"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-[#EEEDFF] text-[#4A47C4]"><MessageSquareText/></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#0F9D8C]">Continue where you left off</p><h1 className="mt-2 truncate font-sora text-2xl font-bold md:text-3xl">{data.quotes[0].details}</h1><p className="mt-2 text-sm text-[#6B7280]">Status: <span className="font-semibold capitalize text-[#A56A00]">{data.quotes[0].status}</span> · Review the latest activity and keep your request moving.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold text-white">Open request <ArrowRight size={16}/></button></div></DashboardCard>:<section className="overflow-hidden rounded-[20px] bg-[#1E1B6E] p-6 text-white md:p-9"><p className="text-sm font-semibold text-[#78DBD0]">Welcome, {firstName}. Let&apos;s get your first project moving.</p><h1 className="mt-3 max-w-2xl font-sora text-3xl font-bold md:text-4xl">The right professional is three simple steps away.</h1><div className="mt-8 grid gap-4 md:grid-cols-3"><Step number="01" title="Tell us what you need" copy="Search by service and location."/><Step number="02" title="Compare trusted pros" copy="Check verification and real reviews."/><Step number="03" title="Get your quotes" copy="Choose confidently and track replies."/></div><Link href="/businesses" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#0F9D8C] px-5 py-3 text-sm font-semibold">Find a professional <ArrowRight size={16}/></Link></section>}
 <section className="overflow-x-auto rounded-xl border border-[#E4E7EC] bg-white"><div className="flex min-w-[680px] divide-x divide-[#E8EAF0]">{[[<MessageSquareText key="q"/>,data.quotes.length,'Quote requests'],[<Bell key="n"/>,unread,'Unread updates'],[<Heart key="s"/>,data.favorites.length,'Saved pros'],[<CheckCircle2 key="a"/>,active.length,'Active requests']].map(([icon,value,label])=><div key={String(label)} className="flex flex-1 items-center gap-3 px-5 py-4"><span className="text-[#596174]">{icon}</span><p className="font-sora text-xl font-bold tabular-nums">{value as number}</p><p className="text-xs text-[#8A91A1]">{label as string}</p></div>)}</div></section>
 <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#0F9D8C]">Discover</p><h2 className="mt-1 font-sora text-2xl font-bold">Recommended for you</h2></div><Link href="/businesses" className="hidden items-center gap-1 text-sm font-semibold text-[#0F9D8C] sm:flex">Browse all <ArrowRight size={15}/></Link></div>{data.recommendations.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.recommendations.slice(0,6).map(item=><ProfessionalCard key={item.business.id} item={item}/>)}</div>:<DashboardCard className="rounded-xl p-6"><p className="text-sm text-[#667085]">No verified recommendations are available in your area yet.</p></DashboardCard>}</section>
 <div className="grid gap-7 xl:grid-cols-[1.4fr_1fr]"><Panel title="Recent requests" subtitle="Track quotes and provider replies" action="View all">{data.quotes.length?<div className="divide-y divide-[#EEF0F4]">{data.quotes.slice(0,4).map(q=><QuoteRow key={q.id} quote={q}/>)}</div>:<CustomerEmpty kind="requests"/>}</Panel><div className="space-y-7"><Panel title="Your shortlist" subtitle="Saved professionals ready to compare" action="Compare">{data.favorites.length?<div className="space-y-2">{data.favorites.slice(0,4).map(b=><Link key={b.id} href={`/businesses/${b.id}`} className="flex items-center gap-3 rounded-lg p-3 hover:bg-[#F7F8FA]"><span className="grid size-10 place-items-center rounded-lg bg-[#EEEDFF] font-bold text-[#4A47C4]">{b.name.charAt(0)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{b.name}</p><p className="text-xs text-[#8A91A1]">{b.city}</p></div><ChevronRight size={16}/></Link>)}</div>:<CustomerEmpty kind="saved"/>}</Panel><Panel title="Notifications" subtitle="Replies, quotes, and reminders" action="View all">{data.notifications.length?data.notifications.slice(0,3).map(n=><Notice key={n.id} note={n}/>):<p className="py-7 text-center text-sm text-[#8A91A1]">You&apos;re all caught up.</p>}</Panel></div></div>
 </div>}
function Step({number,title,copy}:{number:string;title:string;copy:string}){return <div className="rounded-xl border border-white/10 bg-white/[.06] p-5"><p className="font-mono text-xs text-[#78DBD0]">{number}</p><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">{copy}</p></div>}
function ProfessionalCard({item}:{item:Recommendation}){const b=item.business;return <Link href={`/businesses/${b.id}`}><DashboardCard interactive className="h-full overflow-hidden rounded-xl"><div className="relative h-28 bg-gradient-to-br from-[#E8F7F5] to-[#EEEDFF]"><span className="absolute bottom-3 left-4 grid size-14 place-items-center rounded-xl border-2 border-white bg-[#1E1B6E] text-lg font-bold text-white">{b.name.charAt(0)}</span>{b.is_verified&&<span className="absolute right-3 top-3 rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-[#237A4B] shadow-sm">Verified</span>}</div><div className="p-4"><p className="font-sora font-bold">{b.name}</p><p className="mt-1 text-xs text-[#8A91A1]">{item.category} · {b.city}</p><div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1 text-sm font-semibold"><Star size={14} className="text-[#FFB800]" fill="currentColor"/>{item.reviewCount?item.rating.toFixed(1):'New'} <span className="font-normal text-[#9CA3AF]">({item.reviewCount})</span></span><span className="text-xs font-semibold text-[#0F9D8C]">View profile</span></div></div></DashboardCard></Link>}
function CustomerEmpty({kind}:{kind:'requests'|'saved'}){return <div className="grid min-h-52 place-items-center p-6 text-center"><div><svg viewBox="0 0 150 90" className="mx-auto h-20 w-36" aria-hidden="true"><rect x="35" y="15" width="80" height="58" rx="9" fill="#F2F4F7" stroke="#CDD2DC" strokeWidth="2"/><path d="M53 34h44M53 45h29" stroke="#A3AAB8" strokeWidth="3" strokeLinecap="round"/><circle cx="105" cy="67" r="15" fill="#E4F6F2"/><path d={kind==='requests'?'M98 67h14M105 60v14':'M99 62c4-5 12 0 6 8-6-8-14-3-6-8Z'} stroke="#0F9D8C" strokeWidth="2.5" fill="none" strokeLinecap="round"/></svg><p className="mt-3 text-sm font-semibold">{kind==='requests'?'Start your first request':'Build your shortlist'}</p><p className="mt-1 text-xs text-[#8A91A1]">{kind==='requests'?'Tell a professional what you need and compare quotes.':'Save trusted professionals to compare them later.'}</p><Link href="/businesses" className="mt-4 inline-flex rounded-lg bg-[#0F9D8C] px-4 py-2 text-xs font-semibold text-white">{kind==='requests'?'Find a professional':'Explore professionals'}</Link></div></div>}
function Nav({href,pathname,icon,label,badge,primary}:{href:string;pathname:string;icon:React.ReactNode;label:string;badge?:number;primary?:boolean}){const active=pathname===href||pathname.startsWith(`${href}/`);return <Link href={href} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm transition ${active||primary?'bg-[#0F9D8C] font-semibold text-white shadow-lg shadow-black/10':'text-white/60 hover:bg-white/10 hover:text-white'}`}>{icon}{label}{!!badge&&<span className="ml-auto rounded-full bg-[#F4623A] px-2 py-0.5 text-[10px]">{badge}</span>}</Link>}
function Metric({icon,label,value,note,color}:{icon:React.ReactNode;label:string;value:number|string;note:string;color:'teal'|'coral'|'indigo'|'green'}){const c={teal:'bg-[#DFF7F3] text-[#0F9D8C]',coral:'bg-[#FFF0EB] text-[#F4623A]',indigo:'bg-[#EEEDFF] text-[#4A47C4]',green:'bg-[#EAF8EF] text-[#24945A]'};return <DashboardCard className="rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-sm text-[#6B7280]">{label}</p><p className="mt-2 font-sora text-3xl font-bold tabular-nums">{value}</p></div><span className={`grid size-11 place-items-center rounded-xl ${c[color]}`}>{icon}</span></div><p className="mt-4 text-xs text-[#9CA3AF]">{note}</p></DashboardCard>}
function Panel({title,subtitle,action,children}:{title:string;subtitle:string;action:string;children:React.ReactNode}){return <DashboardCard className="overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-[#EEF0F4] p-5 md:px-6"><div><h2 className="font-sora text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-[#9CA3AF]">{subtitle}</p></div><button className="text-xs font-semibold text-[#0F9D8C]">{action}</button></div><div className="p-3 md:p-4">{children}</div></DashboardCard>}
function QuoteRow({quote}:{quote:Quote}){return <div className="flex items-center gap-4 px-2 py-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#EEEDFF] text-[#4A47C4]"><BriefcaseBusiness size={19}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{quote.details}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#9CA3AF]"><Clock3 size={12}/>{new Date(quote.created_at).toLocaleDateString()}</p></div>{quote.budget!==null&&<p className="hidden text-sm font-bold sm:block">PKR {quote.budget.toLocaleString()}</p>}<span className="rounded-full bg-[#FFF7E6] px-3 py-1 text-[11px] font-semibold capitalize text-[#A56A00]">{quote.status}</span><ChevronRight size={17} className="text-[#C5C9D2]"/></div>}
function Notice({note}:{note:Notification}){return <div className="flex gap-3 rounded-xl p-3 hover:bg-[#F7F8FA]"><span className={`mt-1 size-2 shrink-0 rounded-full ${note.is_read?'bg-[#D1D5DB]':'bg-[#0F9D8C]'}`}/><div><p className="text-sm font-semibold">{note.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#6B7280]">{note.message}</p></div></div>}
function Empty({icon,title,copy,href}:{icon:React.ReactNode;title:string;copy:string;href:string}){return <div className="grid min-h-64 place-items-center p-6 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#DFF7F3] text-[#0F9D8C]">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-[#9CA3AF]">{copy}</p><Link href={href} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[#0F9D8C]">Get started <ArrowRight size={15}/></Link></div></div>}
function Progress({completion,completed}:{completion:number;completed:boolean}){return <section className="rounded-2xl bg-gradient-to-br from-[#0F9D8C] to-[#08796E] p-6 text-white"><div className="flex justify-between"><div><p className="text-sm text-white/70">Profile strength</p><p className="mt-1 font-sora text-3xl font-bold">{completion}%</p></div><CircleDollarSign size={34} className="text-white/50"/></div><div className="mt-5 h-2 rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{width:`${completion}%`}}/></div><p className="mt-4 text-xs text-white/70">{completed?'Your profile is ready to attract customers.':'Complete onboarding to improve trust and visibility.'}</p></section>}
function Saved({favorites}:{favorites:Business[]}){return <section className="rounded-2xl bg-gradient-to-br from-[#1E1B6E] to-[#34308F] p-6 text-white"><div className="flex justify-between"><div><p className="text-sm text-white/60">Your shortlist</p><p className="mt-1 font-sora text-3xl font-bold">{favorites.length} saved</p></div><Heart className="text-[#F58A6D]" fill="currentColor"/></div><Link href="/businesses" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#7DE0D4]">Explore professionals <ArrowRight size={15}/></Link></section>}
function Skeleton(){return <div className="animate-pulse space-y-6"><div className="h-64 rounded-[28px] bg-[#1E1B6E]/15"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-36 rounded-2xl bg-white"/>)}</div></div>}
